/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs.index'
import { Route as TabsScheduleRouteImport } from './routes/_tabs.schedule'
import { Route as TabsQuickLogRouteImport } from './routes/_tabs.quick-log'
import { Route as TabsGalleryRouteImport } from './routes/_tabs.gallery'
import { Route as TabsAttendanceRouteImport } from './routes/_tabs.attendance'
import { Route as TabsAlertsRouteImport } from './routes/_tabs.alerts'
import { Route as TabsReportsIndexRouteImport } from './routes/_tabs.reports.index'
import { Route as TabsMessagesIndexRouteImport } from './routes/_tabs.messages.index'
import { Route as TabsChildrenIndexRouteImport } from './routes/_tabs.children.index'
import { Route as TabsAccountIndexRouteImport } from './routes/_tabs.account.index'
import { Route as TabsReportsWeekRouteImport } from './routes/_tabs.reports.week'
import { Route as TabsMessagesAnnouncementsRouteImport } from './routes/_tabs.messages.announcements'
import { Route as TabsMessagesThreadIdRouteImport } from './routes/_tabs.messages.$threadId'
import { Route as TabsLogPhotoRouteImport } from './routes/_tabs.log.photo'
import { Route as TabsLogNoteRouteImport } from './routes/_tabs.log.note'
import { Route as TabsLogIncidentRouteImport } from './routes/_tabs.log.incident'
import { Route as TabsAttendanceSummaryRouteImport } from './routes/_tabs.attendance.summary'
import { Route as TabsAttendanceScanRouteImport } from './routes/_tabs.attendance.scan'
import { Route as TabsAccountProfileRouteImport } from './routes/_tabs.account.profile'
import { Route as TabsAccountPreferencesRouteImport } from './routes/_tabs.account.preferences'
import { Route as TabsAccountHelpRouteImport } from './routes/_tabs.account.help'
import { Route as TabsChildrenIdIndexRouteImport } from './routes/_tabs.children.$id.index'
import { Route as TabsChildrenIdReportRouteImport } from './routes/_tabs.children.$id.report'
import { Route as TabsChildrenIdPickupRouteImport } from './routes/_tabs.children.$id.pickup'
import { Route as TabsChildrenIdPersonalRouteImport } from './routes/_tabs.children.$id.personal'
import { Route as TabsChildrenIdMedicalRouteImport } from './routes/_tabs.children.$id.medical'
import { Route as TabsChildrenIdHistoryRouteImport } from './routes/_tabs.children.$id.history'
import { Route as TabsChildrenIdEmergencyRouteImport } from './routes/_tabs.children.$id.emergency'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsScheduleRoute = TabsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TabsRoute,
} as any)
const TabsQuickLogRoute = TabsQuickLogRouteImport.update({
  id: '/quick-log',
  path: '/quick-log',
  getParentRoute: () => TabsRoute,
} as any)
const TabsGalleryRoute = TabsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAttendanceRoute = TabsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAlertsRoute = TabsAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => TabsRoute,
} as any)
const TabsReportsIndexRoute = TabsReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMessagesIndexRoute = TabsMessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIndexRoute = TabsChildrenIndexRouteImport.update({
  id: '/children/',
  path: '/children/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountIndexRoute = TabsAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsReportsWeekRoute = TabsReportsWeekRouteImport.update({
  id: '/reports/week',
  path: '/reports/week',
  getParentRoute: () => TabsRoute,
} as any)
const TabsMessagesAnnouncementsRoute =
  TabsMessagesAnnouncementsRouteImport.update({
    id: '/messages/announcements',
    path: '/messages/announcements',
    getParentRoute: () => TabsRoute,
  } as any)
const TabsMessagesThreadIdRoute = TabsMessagesThreadIdRouteImport.update({
  id: '/messages/$threadId',
  path: '/messages/$threadId',
  getParentRoute: () => TabsRoute,
} as any)
const TabsLogPhotoRoute = TabsLogPhotoRouteImport.update({
  id: '/log/photo',
  path: '/log/photo',
  getParentRoute: () => TabsRoute,
} as any)
const TabsLogNoteRoute = TabsLogNoteRouteImport.update({
  id: '/log/note',
  path: '/log/note',
  getParentRoute: () => TabsRoute,
} as any)
const TabsLogIncidentRoute = TabsLogIncidentRouteImport.update({
  id: '/log/incident',
  path: '/log/incident',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAttendanceSummaryRoute = TabsAttendanceSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => TabsAttendanceRoute,
} as any)
const TabsAttendanceScanRoute = TabsAttendanceScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => TabsAttendanceRoute,
} as any)
const TabsAccountProfileRoute = TabsAccountProfileRouteImport.update({
  id: '/account/profile',
  path: '/account/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountPreferencesRoute = TabsAccountPreferencesRouteImport.update({
  id: '/account/preferences',
  path: '/account/preferences',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountHelpRoute = TabsAccountHelpRouteImport.update({
  id: '/account/help',
  path: '/account/help',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIdIndexRoute = TabsChildrenIdIndexRouteImport.update({
  id: '/children/$id/',
  path: '/children/$id/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIdReportRoute = TabsChildrenIdReportRouteImport.update({
  id: '/children/$id/report',
  path: '/children/$id/report',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIdPickupRoute = TabsChildrenIdPickupRouteImport.update({
  id: '/children/$id/pickup',
  path: '/children/$id/pickup',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIdPersonalRoute = TabsChildrenIdPersonalRouteImport.update({
  id: '/children/$id/personal',
  path: '/children/$id/personal',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIdMedicalRoute = TabsChildrenIdMedicalRouteImport.update({
  id: '/children/$id/medical',
  path: '/children/$id/medical',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIdHistoryRoute = TabsChildrenIdHistoryRouteImport.update({
  id: '/children/$id/history',
  path: '/children/$id/history',
  getParentRoute: () => TabsRoute,
} as any)
const TabsChildrenIdEmergencyRoute = TabsChildrenIdEmergencyRouteImport.update({
  id: '/children/$id/emergency',
  path: '/children/$id/emergency',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof TabsAlertsRoute
  '/attendance': typeof TabsAttendanceRouteWithChildren
  '/gallery': typeof TabsGalleryRoute
  '/quick-log': typeof TabsQuickLogRoute
  '/schedule': typeof TabsScheduleRoute
  '/account/help': typeof TabsAccountHelpRoute
  '/account/preferences': typeof TabsAccountPreferencesRoute
  '/account/profile': typeof TabsAccountProfileRoute
  '/attendance/scan': typeof TabsAttendanceScanRoute
  '/attendance/summary': typeof TabsAttendanceSummaryRoute
  '/log/incident': typeof TabsLogIncidentRoute
  '/log/note': typeof TabsLogNoteRoute
  '/log/photo': typeof TabsLogPhotoRoute
  '/messages/$threadId': typeof TabsMessagesThreadIdRoute
  '/messages/announcements': typeof TabsMessagesAnnouncementsRoute
  '/reports/week': typeof TabsReportsWeekRoute
  '/account/': typeof TabsAccountIndexRoute
  '/children/': typeof TabsChildrenIndexRoute
  '/messages/': typeof TabsMessagesIndexRoute
  '/reports/': typeof TabsReportsIndexRoute
  '/children/$id/emergency': typeof TabsChildrenIdEmergencyRoute
  '/children/$id/history': typeof TabsChildrenIdHistoryRoute
  '/children/$id/medical': typeof TabsChildrenIdMedicalRoute
  '/children/$id/personal': typeof TabsChildrenIdPersonalRoute
  '/children/$id/pickup': typeof TabsChildrenIdPickupRoute
  '/children/$id/report': typeof TabsChildrenIdReportRoute
  '/children/$id/': typeof TabsChildrenIdIndexRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof TabsAlertsRoute
  '/attendance': typeof TabsAttendanceRouteWithChildren
  '/gallery': typeof TabsGalleryRoute
  '/quick-log': typeof TabsQuickLogRoute
  '/schedule': typeof TabsScheduleRoute
  '/': typeof TabsIndexRoute
  '/account/help': typeof TabsAccountHelpRoute
  '/account/preferences': typeof TabsAccountPreferencesRoute
  '/account/profile': typeof TabsAccountProfileRoute
  '/attendance/scan': typeof TabsAttendanceScanRoute
  '/attendance/summary': typeof TabsAttendanceSummaryRoute
  '/log/incident': typeof TabsLogIncidentRoute
  '/log/note': typeof TabsLogNoteRoute
  '/log/photo': typeof TabsLogPhotoRoute
  '/messages/$threadId': typeof TabsMessagesThreadIdRoute
  '/messages/announcements': typeof TabsMessagesAnnouncementsRoute
  '/reports/week': typeof TabsReportsWeekRoute
  '/account': typeof TabsAccountIndexRoute
  '/children': typeof TabsChildrenIndexRoute
  '/messages': typeof TabsMessagesIndexRoute
  '/reports': typeof TabsReportsIndexRoute
  '/children/$id/emergency': typeof TabsChildrenIdEmergencyRoute
  '/children/$id/history': typeof TabsChildrenIdHistoryRoute
  '/children/$id/medical': typeof TabsChildrenIdMedicalRoute
  '/children/$id/personal': typeof TabsChildrenIdPersonalRoute
  '/children/$id/pickup': typeof TabsChildrenIdPickupRoute
  '/children/$id/report': typeof TabsChildrenIdReportRoute
  '/children/$id': typeof TabsChildrenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_tabs/alerts': typeof TabsAlertsRoute
  '/_tabs/attendance': typeof TabsAttendanceRouteWithChildren
  '/_tabs/gallery': typeof TabsGalleryRoute
  '/_tabs/quick-log': typeof TabsQuickLogRoute
  '/_tabs/schedule': typeof TabsScheduleRoute
  '/_tabs/': typeof TabsIndexRoute
  '/_tabs/account/help': typeof TabsAccountHelpRoute
  '/_tabs/account/preferences': typeof TabsAccountPreferencesRoute
  '/_tabs/account/profile': typeof TabsAccountProfileRoute
  '/_tabs/attendance/scan': typeof TabsAttendanceScanRoute
  '/_tabs/attendance/summary': typeof TabsAttendanceSummaryRoute
  '/_tabs/log/incident': typeof TabsLogIncidentRoute
  '/_tabs/log/note': typeof TabsLogNoteRoute
  '/_tabs/log/photo': typeof TabsLogPhotoRoute
  '/_tabs/messages/$threadId': typeof TabsMessagesThreadIdRoute
  '/_tabs/messages/announcements': typeof TabsMessagesAnnouncementsRoute
  '/_tabs/reports/week': typeof TabsReportsWeekRoute
  '/_tabs/account/': typeof TabsAccountIndexRoute
  '/_tabs/children/': typeof TabsChildrenIndexRoute
  '/_tabs/messages/': typeof TabsMessagesIndexRoute
  '/_tabs/reports/': typeof TabsReportsIndexRoute
  '/_tabs/children/$id/emergency': typeof TabsChildrenIdEmergencyRoute
  '/_tabs/children/$id/history': typeof TabsChildrenIdHistoryRoute
  '/_tabs/children/$id/medical': typeof TabsChildrenIdMedicalRoute
  '/_tabs/children/$id/personal': typeof TabsChildrenIdPersonalRoute
  '/_tabs/children/$id/pickup': typeof TabsChildrenIdPickupRoute
  '/_tabs/children/$id/report': typeof TabsChildrenIdReportRoute
  '/_tabs/children/$id/': typeof TabsChildrenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/alerts'
    | '/attendance'
    | '/gallery'
    | '/quick-log'
    | '/schedule'
    | '/account/help'
    | '/account/preferences'
    | '/account/profile'
    | '/attendance/scan'
    | '/attendance/summary'
    | '/log/incident'
    | '/log/note'
    | '/log/photo'
    | '/messages/$threadId'
    | '/messages/announcements'
    | '/reports/week'
    | '/account/'
    | '/children/'
    | '/messages/'
    | '/reports/'
    | '/children/$id/emergency'
    | '/children/$id/history'
    | '/children/$id/medical'
    | '/children/$id/personal'
    | '/children/$id/pickup'
    | '/children/$id/report'
    | '/children/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/alerts'
    | '/attendance'
    | '/gallery'
    | '/quick-log'
    | '/schedule'
    | '/'
    | '/account/help'
    | '/account/preferences'
    | '/account/profile'
    | '/attendance/scan'
    | '/attendance/summary'
    | '/log/incident'
    | '/log/note'
    | '/log/photo'
    | '/messages/$threadId'
    | '/messages/announcements'
    | '/reports/week'
    | '/account'
    | '/children'
    | '/messages'
    | '/reports'
    | '/children/$id/emergency'
    | '/children/$id/history'
    | '/children/$id/medical'
    | '/children/$id/personal'
    | '/children/$id/pickup'
    | '/children/$id/report'
    | '/children/$id'
  id:
    | '__root__'
    | '/_tabs'
    | '/sitemap.xml'
    | '/_tabs/alerts'
    | '/_tabs/attendance'
    | '/_tabs/gallery'
    | '/_tabs/quick-log'
    | '/_tabs/schedule'
    | '/_tabs/'
    | '/_tabs/account/help'
    | '/_tabs/account/preferences'
    | '/_tabs/account/profile'
    | '/_tabs/attendance/scan'
    | '/_tabs/attendance/summary'
    | '/_tabs/log/incident'
    | '/_tabs/log/note'
    | '/_tabs/log/photo'
    | '/_tabs/messages/$threadId'
    | '/_tabs/messages/announcements'
    | '/_tabs/reports/week'
    | '/_tabs/account/'
    | '/_tabs/children/'
    | '/_tabs/messages/'
    | '/_tabs/reports/'
    | '/_tabs/children/$id/emergency'
    | '/_tabs/children/$id/history'
    | '/_tabs/children/$id/medical'
    | '/_tabs/children/$id/personal'
    | '/_tabs/children/$id/pickup'
    | '/_tabs/children/$id/report'
    | '/_tabs/children/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/schedule': {
      id: '/_tabs/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof TabsScheduleRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/quick-log': {
      id: '/_tabs/quick-log'
      path: '/quick-log'
      fullPath: '/quick-log'
      preLoaderRoute: typeof TabsQuickLogRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/gallery': {
      id: '/_tabs/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof TabsGalleryRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/attendance': {
      id: '/_tabs/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof TabsAttendanceRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/alerts': {
      id: '/_tabs/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof TabsAlertsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/reports/': {
      id: '/_tabs/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof TabsReportsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/messages/': {
      id: '/_tabs/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof TabsMessagesIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/': {
      id: '/_tabs/children/'
      path: '/children'
      fullPath: '/children/'
      preLoaderRoute: typeof TabsChildrenIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account/': {
      id: '/_tabs/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof TabsAccountIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/reports/week': {
      id: '/_tabs/reports/week'
      path: '/reports/week'
      fullPath: '/reports/week'
      preLoaderRoute: typeof TabsReportsWeekRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/messages/announcements': {
      id: '/_tabs/messages/announcements'
      path: '/messages/announcements'
      fullPath: '/messages/announcements'
      preLoaderRoute: typeof TabsMessagesAnnouncementsRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/messages/$threadId': {
      id: '/_tabs/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof TabsMessagesThreadIdRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/log/photo': {
      id: '/_tabs/log/photo'
      path: '/log/photo'
      fullPath: '/log/photo'
      preLoaderRoute: typeof TabsLogPhotoRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/log/note': {
      id: '/_tabs/log/note'
      path: '/log/note'
      fullPath: '/log/note'
      preLoaderRoute: typeof TabsLogNoteRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/log/incident': {
      id: '/_tabs/log/incident'
      path: '/log/incident'
      fullPath: '/log/incident'
      preLoaderRoute: typeof TabsLogIncidentRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/attendance/summary': {
      id: '/_tabs/attendance/summary'
      path: '/summary'
      fullPath: '/attendance/summary'
      preLoaderRoute: typeof TabsAttendanceSummaryRouteImport
      parentRoute: typeof TabsAttendanceRoute
    }
    '/_tabs/attendance/scan': {
      id: '/_tabs/attendance/scan'
      path: '/scan'
      fullPath: '/attendance/scan'
      preLoaderRoute: typeof TabsAttendanceScanRouteImport
      parentRoute: typeof TabsAttendanceRoute
    }
    '/_tabs/account/profile': {
      id: '/_tabs/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof TabsAccountProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account/preferences': {
      id: '/_tabs/account/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof TabsAccountPreferencesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account/help': {
      id: '/_tabs/account/help'
      path: '/account/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof TabsAccountHelpRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/$id/': {
      id: '/_tabs/children/$id/'
      path: '/children/$id'
      fullPath: '/children/$id/'
      preLoaderRoute: typeof TabsChildrenIdIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/$id/report': {
      id: '/_tabs/children/$id/report'
      path: '/children/$id/report'
      fullPath: '/children/$id/report'
      preLoaderRoute: typeof TabsChildrenIdReportRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/$id/pickup': {
      id: '/_tabs/children/$id/pickup'
      path: '/children/$id/pickup'
      fullPath: '/children/$id/pickup'
      preLoaderRoute: typeof TabsChildrenIdPickupRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/$id/personal': {
      id: '/_tabs/children/$id/personal'
      path: '/children/$id/personal'
      fullPath: '/children/$id/personal'
      preLoaderRoute: typeof TabsChildrenIdPersonalRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/$id/medical': {
      id: '/_tabs/children/$id/medical'
      path: '/children/$id/medical'
      fullPath: '/children/$id/medical'
      preLoaderRoute: typeof TabsChildrenIdMedicalRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/$id/history': {
      id: '/_tabs/children/$id/history'
      path: '/children/$id/history'
      fullPath: '/children/$id/history'
      preLoaderRoute: typeof TabsChildrenIdHistoryRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/children/$id/emergency': {
      id: '/_tabs/children/$id/emergency'
      path: '/children/$id/emergency'
      fullPath: '/children/$id/emergency'
      preLoaderRoute: typeof TabsChildrenIdEmergencyRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsAttendanceRouteChildren {
  TabsAttendanceScanRoute: typeof TabsAttendanceScanRoute
  TabsAttendanceSummaryRoute: typeof TabsAttendanceSummaryRoute
}

const TabsAttendanceRouteChildren: TabsAttendanceRouteChildren = {
  TabsAttendanceScanRoute: TabsAttendanceScanRoute,
  TabsAttendanceSummaryRoute: TabsAttendanceSummaryRoute,
}

const TabsAttendanceRouteWithChildren = TabsAttendanceRoute._addFileChildren(
  TabsAttendanceRouteChildren,
)

interface TabsRouteChildren {
  TabsAlertsRoute: typeof TabsAlertsRoute
  TabsAttendanceRoute: typeof TabsAttendanceRouteWithChildren
  TabsGalleryRoute: typeof TabsGalleryRoute
  TabsQuickLogRoute: typeof TabsQuickLogRoute
  TabsScheduleRoute: typeof TabsScheduleRoute
  TabsIndexRoute: typeof TabsIndexRoute
  TabsAccountHelpRoute: typeof TabsAccountHelpRoute
  TabsAccountPreferencesRoute: typeof TabsAccountPreferencesRoute
  TabsAccountProfileRoute: typeof TabsAccountProfileRoute
  TabsLogIncidentRoute: typeof TabsLogIncidentRoute
  TabsLogNoteRoute: typeof TabsLogNoteRoute
  TabsLogPhotoRoute: typeof TabsLogPhotoRoute
  TabsMessagesThreadIdRoute: typeof TabsMessagesThreadIdRoute
  TabsMessagesAnnouncementsRoute: typeof TabsMessagesAnnouncementsRoute
  TabsReportsWeekRoute: typeof TabsReportsWeekRoute
  TabsAccountIndexRoute: typeof TabsAccountIndexRoute
  TabsChildrenIndexRoute: typeof TabsChildrenIndexRoute
  TabsMessagesIndexRoute: typeof TabsMessagesIndexRoute
  TabsReportsIndexRoute: typeof TabsReportsIndexRoute
  TabsChildrenIdEmergencyRoute: typeof TabsChildrenIdEmergencyRoute
  TabsChildrenIdHistoryRoute: typeof TabsChildrenIdHistoryRoute
  TabsChildrenIdMedicalRoute: typeof TabsChildrenIdMedicalRoute
  TabsChildrenIdPersonalRoute: typeof TabsChildrenIdPersonalRoute
  TabsChildrenIdPickupRoute: typeof TabsChildrenIdPickupRoute
  TabsChildrenIdReportRoute: typeof TabsChildrenIdReportRoute
  TabsChildrenIdIndexRoute: typeof TabsChildrenIdIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAlertsRoute: TabsAlertsRoute,
  TabsAttendanceRoute: TabsAttendanceRouteWithChildren,
  TabsGalleryRoute: TabsGalleryRoute,
  TabsQuickLogRoute: TabsQuickLogRoute,
  TabsScheduleRoute: TabsScheduleRoute,
  TabsIndexRoute: TabsIndexRoute,
  TabsAccountHelpRoute: TabsAccountHelpRoute,
  TabsAccountPreferencesRoute: TabsAccountPreferencesRoute,
  TabsAccountProfileRoute: TabsAccountProfileRoute,
  TabsLogIncidentRoute: TabsLogIncidentRoute,
  TabsLogNoteRoute: TabsLogNoteRoute,
  TabsLogPhotoRoute: TabsLogPhotoRoute,
  TabsMessagesThreadIdRoute: TabsMessagesThreadIdRoute,
  TabsMessagesAnnouncementsRoute: TabsMessagesAnnouncementsRoute,
  TabsReportsWeekRoute: TabsReportsWeekRoute,
  TabsAccountIndexRoute: TabsAccountIndexRoute,
  TabsChildrenIndexRoute: TabsChildrenIndexRoute,
  TabsMessagesIndexRoute: TabsMessagesIndexRoute,
  TabsReportsIndexRoute: TabsReportsIndexRoute,
  TabsChildrenIdEmergencyRoute: TabsChildrenIdEmergencyRoute,
  TabsChildrenIdHistoryRoute: TabsChildrenIdHistoryRoute,
  TabsChildrenIdMedicalRoute: TabsChildrenIdMedicalRoute,
  TabsChildrenIdPersonalRoute: TabsChildrenIdPersonalRoute,
  TabsChildrenIdPickupRoute: TabsChildrenIdPickupRoute,
  TabsChildrenIdReportRoute: TabsChildrenIdReportRoute,
  TabsChildrenIdIndexRoute: TabsChildrenIdIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
